services:
  # Python Backend
  - type: web
    name: stylegenie-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --pythonpath src/chatbot --timeout 120 -b 0.0.0.0:$PORT flask_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12

  # Static Frontend (React)
  - type: web
    name: stylegenie-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: stylegenie-backend
          property: host
