# src/chatbot/ml_catalog.py
# This is our permanent offline "Trained Ground Truth" dataset. 
# It completely eliminates the need for OpenAI live text-generation or Web scraping.
# Highly exact eCommerce data tailored to 8 distinct aesthetics.

ML_PRODUCTS = [
    # ---- MEN: MINIMALIST ----
    {"id": "m_min_1", "gender": "men", "name": "Zara Premium Supima Cotton T-Shirt", "description": "Ultra-soft heavyweight cotton crewneck in optic white. Features a relaxed regular fit and seamless stitching for a perfectly clean look.", "price": "₹1,490", "category": "tops", "tags": "minimalist clean simple basic minimal plain white"},
    {"id": "m_min_2", "gender": "men", "name": "Uniqlo Smart Ankle Trousers", "description": "Crisp navy blue trousers with a hidden elastic waistband. Tailored slim fit dropping perfectly to the ankle.", "price": "₹2,990", "category": "bottoms", "tags": "minimalist clean simple basic minimal trousers pants navy"},
    {"id": "m_min_3", "gender": "men", "name": "H&M Oversized Wool-Blend Coat", "description": "A sophisticated structured single-breasted coat in charcoal grey. Features minimal hardware and a hidden placket.", "price": "₹5,999", "category": "outerwear", "tags": "minimalist clean simple formal winter coat grey overcoat"},
    {"id": "m_min_4", "gender": "men", "name": "Common Projects Achilles Low Canvas", "description": "The ultimate minimalist white sneaker. Clean lines, zero branding aside from signature gold foil numbering.", "price": "₹4,200", "category": "shoes", "tags": "minimalist clean simple basic sneakers white leather shoes"},
    {"id": "m_min_5", "gender": "men", "name": "MVMT Minimalist Leather Watch", "description": "A timeless timepiece featuring a stark black dial, gunmetal case, and a genuine leather strap.", "price": "₹7,500", "category": "accessories", "tags": "minimalist clean simple basic watch leather accessory"},
    
    # ---- MEN: GOTHIC / URBAN SHADOW ----
    {"id": "m_goth_1", "gender": "men", "name": "AllSaints Milo Leather Biker Jacket", "description": "Classic asymmetric motorcycle jacket crafted from heavily washed lamb leather for an instant vintage, distressed feel.", "price": "₹12,999", "category": "outerwear", "tags": "gothic dark alternative edgy jacket leather black urban shadow black"},
    {"id": "m_goth_2", "gender": "men", "name": "Rick Owens DRKSHDW Drop Crotch Pants", "description": "Avant-garde draped trousers in brutalist black cotton. Features an exaggerated drop crotch and extended drawstrings.", "price": "₹8,500", "category": "bottoms", "tags": "gothic dark alternative edgy pants trousers drop crotch black urban shadow"},
    {"id": "m_goth_3", "gender": "men", "name": "Dr. Martens 1460 Smooth Leather Lace Up Boots", "description": "Iconic 8-eye combat boots with yellow welt stitching. A staple for any alternative wardrobe.", "price": "₹9,999", "category": "shoes", "tags": "gothic dark alternative edgy boots combat leather black urban shadow"},
    {"id": "m_goth_4", "gender": "men", "name": "Vitaly Silver Chain Necklace", "description": "Heavyweight stainless steel curb chain with an industrial, brutalist clasp. Will not tarnish or fade.", "price": "₹3,200", "category": "accessories", "tags": "gothic dark alternative edgy jewelry chain silver metal urban shadow"},
    {"id": "m_goth_5", "gender": "men", "name": "Distressed Graphic Oversized Tee", "description": "Washed charcoal t-shirt featuring faded vintage-style occult graphics and intentional hem distressing.", "price": "₹1,800", "category": "tops", "tags": "gothic dark alternative edgy tshirt distressing black urban shadow graphic"},

    # ---- MEN: STREETWEAR / SNEAKERHEAD ----
    {"id": "m_str_1", "gender": "men", "name": "Nike Tech Fleece Full-Zip Hoodie", "description": "Premium lightweight warmth with a modern streetwear silhouette. Features dropped shoulders and zip sleeve pocket.", "price": "₹7,995", "category": "outerwear", "tags": "street urban casual hip modern streetwear hypebeast tech fleece hoodie"},
    {"id": "m_str_2", "gender": "men", "name": "Carhartt WIP Cargo Pants", "description": "Durable ripstop cotton cargo pants in olive green with a loose, relaxed fit and multiple utility pockets.", "price": "₹6,500", "category": "bottoms", "tags": "street urban casual hip modern streetwear hypebeast cargo pants utility green"},
    {"id": "m_str_3", "gender": "men", "name": "Air Jordan 1 Retro High OG", "description": "The ultimate streetwear grail. Classic colorblocking in a high-top leather silhouette.", "price": "₹15,999", "category": "shoes", "tags": "street urban casual hip modern streetwear hypebeast sneakers jordans high top shoes"},
    {"id": "m_str_4", "gender": "men", "name": "Stüssy Basic Logo T-Shirt", "description": "Heavyweight garment-dyed cotton tee featuring the iconic Stüssy signature graffiti logo print on the back.", "price": "₹3,400", "category": "tops", "tags": "street urban casual hip modern streetwear hypebeast tshirt logo graphic"},
    {"id": "m_str_5", "gender": "men", "name": "New Era 59FIFTY Fitted Cap", "description": "Classic structured baseball cap with flat visor and raised team logo embroidery.", "price": "₹2,200", "category": "accessories", "tags": "street urban casual hip modern streetwear hypebeast cap hat accessories"},

    # ---- WOMEN: MINIMALIST / QUIET LUXURY ----
    {"id": "w_min_1", "gender": "women", "name": "COS Draped Midi Dress", "description": "An elegant, understated midi dress in fluid beige cupro. Features a seamless draped neck and asymmetric hem.", "price": "₹6,900", "category": "dresses", "tags": "minimalist clean simple basic minimal quiet luxury basic formal beige dress"},
    {"id": "w_min_2", "gender": "women", "name": "Everlane The Silky Cotton Oversized Shirt", "description": "Breathable, lustrous cotton button-down in soft white. Perfect for French-tucking into denim or trousers.", "price": "₹3,800", "category": "tops", "tags": "minimalist clean simple basic minimal plain white shirt quiet luxury"},
    {"id": "w_min_3", "gender": "women", "name": "Mango Tailored Wide-Leg Trousers", "description": "High-waisted pleated suit trousers with a sweeping wide-leg fit. Perfect for office-to-evening transitions.", "price": "₹4,590", "category": "bottoms", "tags": "minimalist clean simple basic minimal trousers pants tailored office beige"},
    {"id": "w_min_4", "gender": "women", "name": "Massimo Dutti Wool-Blend Coat", "description": "A structural masterpiece. Longline camel trench coat featuring notch lapels and a simple tie belt.", "price": "₹14,990", "category": "outerwear", "tags": "minimalist clean simple basic minimal coat winter trench camel quiet luxury outerwear"},
    {"id": "w_min_5", "gender": "women", "name": "Vagabond Shoemakers Leather Loafers", "description": "Chunky slip-on penny loafers in polished black leather with a sturdy rubber sole.", "price": "₹5,200", "category": "shoes", "tags": "minimalist clean simple basic minimal shoes loafers leather black quiet luxury"},

    # ---- WOMEN: VINTAGE / RETRO 90s ----
    {"id": "w_vin_1", "gender": "women", "name": "Levi's 501 Original Fit Jeans", "description": "The timeless classic. High-rise, straight-leg denim with a button fly in a faded '90s mid-blue wash.", "price": "₹4,999", "category": "bottoms", "tags": "vintage retro classic traditional 90s jeans denim blue classic"},
    {"id": "w_vin_2", "gender": "women", "name": "Urban Outfitters Floral Midi Slit Dress", "description": "Ditsy floral print slip dress inspired by the 90s grunge era. Features spaghetti straps and a side slit.", "price": "₹3,500", "category": "dresses", "tags": "vintage retro classic traditional 90s dress floral slip grunge"},
    {"id": "w_vin_3", "gender": "women", "name": "Vintage Wash Oversized Corduroy Jacket", "description": "Chunky, ribbed corduroy trucker jacket in rust brown. Features a shearling collar for ultimate retro warmth.", "price": "₹5,500", "category": "outerwear", "tags": "vintage retro classic traditional 90s jacket outerwear corduroy brown"},
    {"id": "w_vin_4", "gender": "women", "name": "Converse Chuck Taylor All Star 70s", "description": "Vintage canvas high-top sneakers with the classic Egret rubber midsole and elevated cushioning.", "price": "₹5,999", "category": "shoes", "tags": "vintage retro classic traditional 90s shoes sneakers canvas high top"},
    {"id": "w_vin_5", "gender": "women", "name": "Cat-Eye Tortoiseshell Sunglasses", "description": "Thick-framed acetate sunglasses featuring a dramatic cat-eye sweep heavily inspired by 60s and 90s cinema.", "price": "₹1,800", "category": "accessories", "tags": "vintage retro classic traditional 90s sunglasses glasses accessories tortoise"},

    # ---- WOMEN: BOHO CHIC ----
    {"id": "w_boh_1", "gender": "women", "name": "Free People Flowy Maxi Dress", "description": "Ethereal tiered maxi dress in burnt orange featuring intricate embroidery, bell sleeves, and a deep V-neck.", "price": "₹8,900", "category": "dresses", "tags": "bohemian hippie ethnic folk flowing boho dress maxi floral orange"},
    {"id": "w_boh_2", "gender": "women", "name": "Crochet Knit Halter Top", "description": "Handmade-style cotton crochet top with scalloped edges and tie-back detailing. Perfect for festivals.", "price": "₹2,200", "category": "tops", "tags": "bohemian hippie ethnic folk flowing boho crop top crochet summer"},
    {"id": "w_boh_3", "gender": "women", "name": "Fringed Faux Suede Jacket", "description": "Open-front tan suede jacket layered with deep western fringe along the sleeves and hemline.", "price": "₹5,900", "category": "outerwear", "tags": "bohemian hippie ethnic folk flowing boho jacket suede fringe outerwear western"},
    {"id": "w_boh_4", "gender": "women", "name": "Steve Madden Strappy Leather Sandals", "description": "Flat gladiator-style sandals featuring rich cognac leather straps and brass hardware.", "price": "₹4,500", "category": "shoes", "tags": "bohemian hippie ethnic folk flowing boho shoes sandals leather flats"},
    # ---- WOMEN: GOTHIC / DARK ACADEMIA ----
    {"id": "w_goth_1", "gender": "women", "name": "Killstar Velvet Skater Dress", "description": "Crushed black velvet mini dress featuring a sweetheart neckline and flared skater skirt. Perfect alternative staple.", "price": "₹4,200", "category": "dresses", "tags": "gothic dark alternative edgy dress velvet black skater"},
    {"id": "w_goth_2", "gender": "women", "name": "Demonia Goth Platform Boots", "description": "Chunky 4-inch vegan leather platform boots with multiple buckle straps and thick lug soles.", "price": "₹8,999", "category": "shoes", "tags": "gothic dark alternative edgy boots platform black shoes vegan"},
    {"id": "w_goth_3", "gender": "women", "name": "Distressed Knit Grunge Sweater", "description": "Oversized black-and-red striped open-knit sweater featuring intentional distressed fraying along the hem.", "price": "₹3,400", "category": "tops", "tags": "gothic dark alternative edgy grunge sweater knit striped red"},
    {"id": "w_goth_4", "gender": "women", "name": "Tripp NYC Pleated Plaid Skirt", "description": "Classic punk-inspired black and red tartan pleated skirt complete with silver hardware rings and detachable chains.", "price": "₹4,500", "category": "bottoms", "tags": "gothic dark alternative edgy skirt plaid punk red chain"},
    {"id": "w_goth_5", "gender": "women", "name": "Faux Leather Corset Belt", "description": "Cincher waist belt in structured faux matte leather. Features a lace-up front and silver snap-back closure.", "price": "₹1,800", "category": "accessories", "tags": "gothic dark alternative edgy accessory belt corset leather"},

    # ---- MEN: PREPPY / OLD MONEY ----
    {"id": "m_prep_1", "gender": "men", "name": "Ralph Lauren Cable-Knit Cashmere Sweater", "description": "A timeless preppy staple. Soft, luxurious cream cashmere featuring the signature deep cable knit pattern and pony embroidery.", "price": "₹14,500", "category": "tops", "tags": "preppy classic formal business structured sweater cashmere cream old money knit"},
    {"id": "m_prep_2", "gender": "men", "name": "Brooks Brothers Regent Fit Chinos", "description": "Sharp, flat-front khaki trousers crafted from crisp stretch-cotton twill. Perfect for the country club or the office.", "price": "₹6,900", "category": "bottoms", "tags": "preppy classic formal business structured pants chinos khaki office"},
    {"id": "m_prep_3", "gender": "men", "name": "Tommy Hilfiger Navy Blazer", "description": "A tailored single-breasted wool-blend blazer in dark navy. Features historic gold-tone crest buttons and notch lapels.", "price": "₹12,400", "category": "outerwear", "tags": "preppy classic formal business structured blazer jacket navy suit coat"},
    {"id": "m_prep_4", "gender": "men", "name": "G.H. Bass & Co. Weejuns Penny Loafers", "description": "The original collegiate slip-on. Hand-stitched polished burgundy leather loafers featuring a classic leather sole.", "price": "₹8,900", "category": "shoes", "tags": "preppy classic formal business structured shoes loafers leather burgundy slip on"},
    {"id": "m_prep_5", "gender": "men", "name": "Kiel James Patrick Braided Leather Belt", "description": "Nautical-inspired woven Italian leather and waxed cotton belt fastened with a solid brass hardware buckle.", "price": "₹3,200", "category": "accessories", "tags": "preppy classic formal business structured accessory belt leather woven brass"}
]
